# Generated by Django 3.0.8 on 2020-08-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='satrter',
            new_name='starter',
        ),
    ]
